### ISSUE TITLE
リアルタイムに同期したい

### ISSUE THREAD

**Issue by volpe28v** [hashrock/taskquest#2]
数秒周期でも良いのでタスクの状態を最新に自動更新すると嬉しい

**Comment by hashrock** [comment]
10秒間隔で自動更新を行うようにしてみました！

**Comment by volpe28v** [comment]
ありがとうございます！

更新はいい感じに出来ているのですが、タスク入力中に更新タイミングが来ちゃうと入力中の文字がクリアされてしまうのと、タスク移動中も同様に戻されてしまいます。
操作中は更新しないなどの制御は可能でしょうか？

**Comment by hashrock** [comment]
ご報告ありがとうございます！確かにそうなってしまってますね。
制御は可能なので、修正したいと思います！

**Comment by hashrock** [comment]
編集中は自動更新を行わないよう、修正しました！

**Comment by volpe28v** [comment]
ありがとうございます！
修正方法も少し考えたのですが Angular がよくわからず・・・勉強になります！
